-- 간단한 문제 9개 정도를 풀어보아요!
-- study.sql
USE studydb;

-- 1번
-- 부서 번호: EMP.DEPTNO, 직무: EMP.JOB, 급여: EMP.SAL
SELECT JOB AS '직무', TRUNCATE(AVG(SAL), -2) AS '급여 평균'
FROM EMP
WHERE DEPTNO = 30
GROUP BY JOB;

-- 2번
-- 부서명: DEPT.DNAME, 부서번호: DEPT.DEPTNO
-- 부서번호: EMP.DEPTNO
SELECT DEPT.DNAME AS '부서명', COUNT(DEPT.DNAME) AS '직원 수'
FROM DEPT
	 INNER JOIN EMP
     ON DEPT.DEPTNO = EMP.DEPTNO
GROUP BY DEPT.DNAME
HAVING COUNT(DEPT.DNAME) >= 4;

-- 3번
SELECT COALESCE(JOB, 'TOTAL') AS '직무명', FORMAT(SUM(SAL), 0) AS '급여의 합'
FROM EMP
GROUP BY JOB WITH ROLLUP;

-- 4번
SELECT ENAME AS '직원명', SAL AS '급여', G.GRADE AS '급여 등급'
FROM EMP E, SALGRADE G
WHERE SAL = (
	SELECT MAX(SAL)
    FROM EMP)
AND E.SAL >= G.LOSAL
AND E.SAL <= G.HISAL;

-- 5번 
SELECT ENAME AS '직원명', CONCAT(FORMAT(SAL+COALESCE(COMM, 0),0), '원') AS '급여'
FROM EMP
WHERE YEAR(HIREDATE) = 1981
ORDER BY SAL+COALESCE(COMM, 0) DESC;

-- 6번
SELECT ENAME AS '직원명', DATE_FORMAT(HIREDATE, '%Y년 %m월 %d일') AS '입사년월일', (
	   CASE
		 WHEN YEAR(HIREDATE) = 1980 THEN 'A'
         WHEN YEAR(HIREDATE) = 1981 THEN 'B'
         WHEN YEAR(HIREDATE) = 1982 THEN 'C'
         WHEN YEAR(HIREDATE) = 1983 THEN 'D'
         ELSE 'not'
		END
        ) AS '그룹'
FROM EMP;

-- 7번
-- 사원 사번: EMPNO, 관리자 사번: MGR
select * from dept;
select * from emp;

SELECT E1.EMPNO AS '사원 사번', E1.ENAME AS '사원 이름', E2.EMPNO AS '관리자 사번', E2.ENAME AS '관리자 이름'
FROM EMP AS E1
	JOIN EMP AS E2
    ON E1.MGR = E2.EMPNO;

-- 8번
SELECT EMPNO, ENAME, EMP.DEPTNO
FROM EMP
	INNER JOIN DEPT
    ON EMP.DEPTNO = DEPT.DEPTNO
    INNER JOIN LOCATIONS
    ON DEPT.LOC_CODE = LOCATIONS.LOC_CODE
WHERE CITY = 'CHICAGO';

-- 9번
SELECT ENAME, SAL
FROM EMP
WHERE SAL >= (
	  SELECT MAX(SAL)
      FROM EMP
      WHERE DEPTNO = 30
      );
